# Generated by Django 3.2.25 on 2025-06-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
