# Generated by Django 3.2.25 on 2025-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cartitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
