# Generated by Django 3.2.25 on 2025-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20250610_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('tonne', 'Tonne'), ('mg', 'Milligram'), ('quintal', 'Quintal'), ('ml', 'Milliliter'), ('l', 'Liter'), ('gallon', 'Gallon'), ('pint', 'Pint'), ('piece', 'Piece'), ('dozen', 'Dozen'), ('pack', 'Pack'), ('box', 'Box')], default='piece', max_length=10),
        ),
    ]
