# Generated by Django 3.2.25 on 2025-06-23 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Enter quantity in a valid format (e.g., '500g', '1 kg', '2 dozen').", regex='^\\s*\\d+(\\.\\d+)?\\s*(g|kg|tonne|mg|quintal|ml|l|gallon|pint|piece|dozen|pack|box)\\s*$')]),
        ),
    ]
