# Generated by Django 3.2.25 on 2025-06-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20250623_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter tax percentage (e.g., 5.00 for 5%)', max_digits=5),
        ),
    ]
