# Generated by Django 3.2.25 on 2025-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20250630_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
