# Generated by Django 3.2.25 on 2025-07-03 23:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20250703_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
