# Generated by Django 3.2.25 on 2025-07-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20250703_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
