# Generated by Django 3.2.25 on 2025-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_cartitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
