# Generated by Django 3.2.25 on 2025-07-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20250710_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='payment_done',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='payment_due',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
