# Generated by Django 3.2.25 on 2025-07-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20250711_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_method',
            field=models.CharField(default='Not Selected', max_length=30),
        ),
    ]
