# Generated by Django 3.2.25 on 2025-07-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_cartitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='payment_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
