# Generated by Django 3.2.25 on 2025-08-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20250808_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='due_amount',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
